.Dd December 1, 2012
.Os
.Dt NULLTTY 1
.Sh NAME
.Nm nulltty
.Nd Simple Unix pseudoterminal relay
.Sh SYNOPSIS
.Nm
.Op Fl d
.Op Fl p Ar pidfile
.Op Fl s Ar signal
.Ar ptyA ptyB
.Nm
.Fl h
.Sh DESCRIPTION
The
.Nm
command creates two pseoduterminal slaves (as symlinks) at the given paths
.Ar ptyA
and
.Ar ptyB
, and then continuously relays data between the two until terminated with
SIGTERM or SIGINT.

If nulltty receives SIGINFO (on platforms which support it) or SIGUSR1, it
will print current relayed byte totals to stderr.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl d
Daemonize the relay
.It Fl p Ar pidfile
Write the relay's PID to
.Ar pidfile
.It Fl s Ar signal
Alert nulltty's parent process with
.Ar signal
when the requested PTYs are ready to be opened.
.Ar signal
can be specified either as a signal number, or with a signal name such as
"INT", "INFO", "USR1", etc.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr socat 1
.Sh AUTHORS
.An "Mark Shroyer" Aq code@markshroyer.com
